language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd --source=$(pwd) --file=/dev/null
  - est --dir=est --file=/dev/null
addons:
  apt:
    packages:
    - libmagic1
    - libmagic-dev
install:
  - gem install pdd
  - gem install est
env:
  global:
    - MAVEN_OPTS="-Xmx256m -Dfile.encoding=UTF-8"
    - JAVA_OPTS="-Xmx256m -Dfile.encoding=UTF-8"
jdk:
  - oraclejdk8
  - oraclejdk7
  #- openjdk6 - jcabi-http doesn't work with JDK 6
