# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "src/test/resources/org/takes/http/keystore",
    "**.json",
    "**.md",
    "**.png",
    "**.svg",
    "**.txt",
    "**.vm",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/CITATION.cff",
    "**/CNAME",
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".pdd",
    "CITATION.cff",
    "CNAME",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
